# Generated by Django 5.0.2 on 2024-05-03 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_signup_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
